version: '3.8'

services:
  explainor-backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - explainor.env
    volumes:
      - maven-cache:/root/.m2
    depends_on:
      - renderer

  renderer:
    build:
      context: ./renderer
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - REMOTION_PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - remotion-cache:/usr/src/app/node_modules/.remotion
      - remotion-browser-cache:/root/.cache

volumes:
  maven-cache:
  remotion-cache:
  remotion-browser-cache:
