version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RENDERER_URL=http://renderer:3030
    depends_on:
      - renderer

  renderer:
    build:
      context: ./renderer
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - PUPPETEER_CACHE_DIR=/root/.cache/puppeteer
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage
    volumes:
      - remotion-cache:/root/.cache

volumes:
  remotion-cache:
