version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RENDERER_URL=http://renderer:3030
    depends_on:
      - renderer

  renderer:
    build:
      context: ./renderer
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
