spring:
  application:
    name: explainor

renderer:
  url: ${RENDERER_URL:http://localhost:3030}

anthropic:
  api:
    key: ${ANTHROPIC_API_KEY}

layout:
  algorithm: graph
  graph:
    layer-spacing: 160.0
    node-spacing: 220.0
    grid-step: 40.0
